### ISSUE TITLE
Config file name mismatch

### ISSUE THREAD

**Issue by 0FiRE0** [ARCANEDEV/LaravelMessenger#16]
- LaravelMessenger Version: 6.0.0
- Laravel Version: 5.8.x
- PHP Version: 7.3.x

### Description:
Hello there,

The config file name used in the "migrations" and "Migration" files is different from the one used in the "Models" and "Traits".

The first one is "laravel-massenger" while the other one is "massenger".

By default, publishing the "ServiceProvider" generates the "massenger" config file.

Could you please either update the "migrations" to use the "massenger" file, or update the "Models" to use the "laravel-massenger".

Kindly find attached a screenshot of the occurrences of using the config file.

![Config file name mismatch](https://user-images.githubusercontent.com/19993814/58834566-628c8400-865c-11e9-9af0-8bed2cc78edf.PNG)

**Comment by arcanedev-maroc** [comment]
Thanks for the feedback :+1:

**Comment by 0FiRE0** [comment]
Most welcome.
Thank you for your fast response +1
