### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mreduar** [ARCANEDEV/LaravelMessenger#21]
I have been using the cmgmyr package for a short time, and I notice that it is slow enough to make queries. I see that you have refactored quite a bit of code and I would like to ask if this represents an improvement in query performance.

**Comment by arcanedev-maroc** [comment]
Hi @MrEduar, sorry about the late response. I didn't see your question.

The rewriting or refactoring of this package is only improve the code quality and maintainability.

### For the performance, it's in your hand:

The **N+1 Queries**, if you forget to eager load your relations in appropriate situations, it can happen with any eloquent model if your not careful.

And it's also mentioned in the documentation: https://laravel.com/docs/6.x/eloquent-relationships#eager-loading

There are tools to detect duplicated queries like https://github.com/barryvdh/laravel-debugbar

And thanks for using this package :+1:
