### ISSUE TITLE
Use On Multiple User Models

### ISSUE THREAD

**Issue by BenQoder** [ARCANEDEV/LaravelMessenger#8]
I Get My User From 2 different Models

How do I implement messages between them?

**Comment by arcanedev-maroc** [comment]
I don't know how to achieve it because the participant is not a polymorphic model.

https://github.com/ARCANEDEV/LaravelMessenger/blob/master/database/migrations/2016_08_01_000003_create_participants_table.php#L45

**Comment by BenQoder** [comment]
I will try to modify the migrations and relationships. I will submit a pull request soon

**Comment by arcanedev-maroc** [comment]
Don't forget to add tests and cover all the new features (100% code coverage) 

Good luck 👍

**Comment by joooseb** [comment]
Is possible in future support multiple models? I want to send messages from admin to user (2 differents guards, multiple auth)

**Comment by arcanedev-maroc** [comment]
PR: #13

**Comment by arcanedev-maroc** [comment]
Released as `v4.0.0` and only available for Laravel `v5.6`
