### ISSUE TITLE
Messaging between multiple models

### ISSUE THREAD

**Issue by mits87** [ARCANEDEV/LaravelMessenger#9]
Hello,

Is it possible to send message between for example admin and user model?
Any plans to support it?

Thank you!

**Comment by arcanedev-maroc** [comment]
Are the `admin` & `user` models stored in different tables ?

> Duplicated: #8

**Comment by mits87** [comment]
Yes, the models are stored in different tables. 
`Admin` and `User` are only example. 

It can be `Admin` / `Customer` / `User` model etc. 
So the participant table should has columns:

```
$table->unsignedBigInteger('model_name');
$table->unsignedBigInteger('model_id');
```

or something like that.

**Comment by arcanedev-maroc** [comment]
The optimal solution is by using the [polymorphic relations
](https://laravel.com/docs/5.5/eloquent-relationships#polymorphic-relations)

Feel free to make a PR 👍 

(I'm closing this issue because it's a duplication #8)

**Comment by arcanedev-maroc** [comment]
Hi @mits87, check https://github.com/ARCANEDEV/LaravelMessenger/issues/8#issuecomment-368571274
